# Generated by Django 3.2.7 on 2021-12-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_type', models.CharField(max_length=5)),
                ('src_port', models.CharField(max_length=7)),
                ('dest_port', models.CharField(max_length=7)),
                ('src_IP', models.CharField(max_length=20)),
                ('dest_IP', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=100)),
            ],
        ),
    ]
